#ifndef __GPS_CONFIG_H__
#define __GPS_CONFIG_H__

#define HIGH_SPEED_BAUD 115200
#define GPS_DEFAULT_BAUD 9600

#define IN_SECOND_START_SIGNAL 2
#define IN_EXPOSURE_START_SIGNAL 3
#define OUT_EXPOSURE_TIME_READY_TO_SEND 4
#define OUT_LED_EXPOSURE_TIME_STAGED 5
#define OUT_LED_EXPOSURE_TIME_SENDING 6

#define IN_SLAVE_SELECT_SS 53
#define IN_SPI_CLOCK_SCK 52
#define IN_MASTER_OUT_SLAVE_IN_MOSI 51
#define OUT_MASTER_IN_SLAVE_OUT_MISO 50

#endif // __GPS_CONFIG_H__

